- name: Instalação do Docker no Debian 11 e AlmaLinux 8
  hosts: docker
  become: yes
  tasks:

    - name: Verificar a distribuição do sistema operacional
      ansible.builtin.setup:
        filter: ansible_distribution

    - name: Instalar pacotes necessários para Docker no Debian 11
      when: ansible_distribution == "Debian"
      block:
        - name: Atualizar cache do APT
          ansible.builtin.apt:
            update_cache: yes

        - name: Instalar dependências
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            state: present

        - name: Adicionar chave GPG do Docker
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/debian/gpg
            state: present

        - name: Adicionar repositório do Docker
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
            state: present

        - name: Instalar Docker
          ansible.builtin.apt:
            name: docker-ce
            state: present
            update_cache: yes

    - name: Instalar pacotes necessários para Docker no AlmaLinux 8
      when: ansible_distribution == "AlmaLinux"
      block:
        - name: Instalar dependências
          ansible.builtin.yum:
            name:
              - yum-utils
              - device-mapper-persistent-data
              - lvm2
            state: present

        - name: Adicionar repositório do Docker
          ansible.builtin.command:
            cmd: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
          args:
            creates: /etc/yum.repos.d/docker-ce.repo

        - name: Instalar Docker
          ansible.builtin.yum:
            name: docker-ce
            state: present

    - name: Habilitar e iniciar o serviço Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Instalando Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Criando link simbólico para Docker Compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link