- name: Configuracao do Lighttpd
  hosts: docker
  become: yes
  vars:
    user: lighttpd
    group: lighttpd
  tasks:
    - name: Verificando distribuição e definindo usuário/grupo
      set_fact:
        user: www-data
        group: www-data
      when: ansible_distribution|lower == 'debian'

    - name: Garantindo o epel-release em AlmaLinux
      package:
        name: epel-release
        state: present
      when: ansible_distribution|lower == 'almalinux'

    - name: Garantindo Lighttpd
      package:
        name: lighttpd
        state: present

    - name: Garantindo que o Lighttpd está ativo e habilitado
      service:
        name: lighttpd
        state: started
        enabled: yes

    - name: Garantindo configuracoes
      template:
        src: '{{ item }}'
        dest: /etc/lighttpd
        owner: root
      loop:
      - /root/playbooks/files/lighttpd.conf
      - /root/playbooks/files/mime-types.conf          

    - name: Garantindo diretórios
      file:
        path: '{{ item }}'
        owner: '{{ user }}'
        group: '{{ group }}'
        state: directory
      loop:
      - /srv/www/html
      - /var/cache/lighttpd
      - /var/logs/lighttpd

    - name: Garantindo configurações de proxy
      blockinfile:
        path: /etc/lighttpd/proxy.conf
        create: yes
        block: |
          $SERVER["socket"] == ":8080" {
            proxy.server = ( "" => ( ( "host" => "192.168.10.10", "port" => "80" )))
          }        

    - name: Garantindo serviço do Lighttpd
      service:
        name: lighttpd
        state: restarted
        enabled: yes

    - name: Garantindo contexto em /srv/www/html
      command: 'restorecon -R /srv/www/html'
      when: ansible_distribution|lower == 'almalinux'