# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/8"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "172.27.11.150"

  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y httpd git
    cd /var/www/html
    rm -rf *
    git clone https://github.com/4linux/4542-site .
    systemctl start httpd
    systemctl enable httpd
  SHELL
end
